Flesh out Symptom Screen
UpstreamInno/guardian_client pull request #34
Opened 2020-04-19 09:34 UTC by AshlandWest

2020-04-19 09:36 UTC, AshlandWest commented
All rebase are belong to us

2020-04-19 11:50 UTC, BranescuMihai requested changes
From the number of files changes, I feel that the first commit is somehow actually a rebase from your feature `onto` master instead of `from`. This will rewrite all project history and is generally[ not a good idea](https://www.atlassian.com/git/tutorials/merging-vs-rebasing#the-golden-rule-of-rebasing).

Since I'm assuming this feature is actually a new screen, I strongly recommend to create a new branch from master, and just add the new changes there, as fixing this would require you look into the git logs and reverting some steps, which is quite advanced

2020-04-19 11:50 UTC, BranescuMihai commented on App.js
> +<<<<<<< HEAD
Some conflict merging indicators were forgotten here, please remove them

2020-04-21 00:26 UTC, luxx commented
Closing this out, feel free to reopen a new one once the conflicts are fixed

2020-04-21 00:26 UTC, closed without merging